=== AlexanderDaniel/utf-x-framework-svn-trunk/lib/utfxdoc/utfxdoc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://utf-x.sourceforge.net/xsd/utfxdoc_1_0/utfxdoc.xsd"
  xmlns:u="http://utf-x.sourceforge.net/xsd/utfxdoc_1_0/utfxdoc.xsd" xmlns:xml="http://www.w3.org/XML/1998/namespace">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
  <xs:complexType name="inline" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="u:class"/>
      <xs:element ref="u:code"/>
      <xs:element ref="u:link"/>
      <xs:element ref="u:img"/>
      <xs:element ref="u:xref"/>
      <xs:element ref="u:xml"/>
    </xs:choice>
  </xs:complexType>
  <xs:group name="block">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="u:para"/>
        <xs:element ref="u:note"/>
        <xs:element ref="u:figure"/>
        <xs:element ref="u:pre"/>
        <xs:element ref="u:xml"/>
        <xs:element ref="u:ordered_list"/>
        <xs:element ref="u:unordered_list"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>
  <xs:element name="document">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="u:title"/>
        <xs:element minOccurs="0" ref="u:subtitle"/>
        <xs:element minOccurs="0" maxOccurs="5" ref="u:author"/>
        <xs:element minOccurs="0" ref="u:version"/>
        <xs:element minOccurs="0" ref="u:date"/>
        <xs:element maxOccurs="unbounded" ref="u:sect1"/>
        <xs:element minOccurs="0" ref="u:glossary"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="subtitle" type="xs:string"/>
  <xs:element name="author" type="xs:string"/>
  <xs:element name="version" type="xs:string"/>
  <xs:element name="date" type="xs:string"/>
  <xs:element name="sect1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="u:title"/>
        <xs:group ref="u:block"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u:sect2"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sect2">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="u:title"/>
        <xs:group ref="u:block"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u:sect3"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sect3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="u:title"/>
        <xs:group ref="u:block"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="para" type="u:inline"/>
  <xs:element name="note" type="u:inline"/>
  <xs:element name="xref">
    <xs:complexType>
      <xs:attribute name="idref" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="link">
    <xs:complexType mixed="true">
      <xs:attribute name="url" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="img">
    <xs:complexType>
      <xs:attribute name="src" use="required"/>
      <xs:attribute name="width" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="svg">
    <xs:complexType>
      <xs:attribute name="src" use="required"/>
      <xs:attribute name="width" use="required"/>
      <xs:attribute name="height" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ordered_list">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="u:item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="unordered_list">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="u:item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="item" type="u:inline"/>
  <xs:element name="class" type="xs:string"/>
  <xs:element name="code" type="xs:string"/>
  <xs:element name="pre" type="xs:string"/>
  <xs:element name="figure">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="u:img"/>
          <xs:element ref="u:xml"/>          
          <xs:element ref="u:svg"/>          
        </xs:choice>
        <xs:element ref="u:caption"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="caption" type="xs:string"/>
  <xs:element name="xml">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="xml:space"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="glossary">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="u:glossary_entry"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="glossary_entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="u:term"/>
        <xs:element ref="u:definition"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="term" type="xs:string"/>
  <xs:element name="definition" type="u:inline"/>
  <xs:complexType name="any" mixed="true">
    <xs:sequence>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip" namespace="##any"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== AlexanderDaniel/utf-x-framework-svn-trunk/doc/devguide/devguide.xml
<?xml version="1.0" encoding="UTF-8"?>
<ud:document xmlns:ud="http://utf-x.sourceforge.net/xsd/utfxdoc_1_0/utfxdoc.xsd"
    xsi:schemaLocation="http://utf-x.sourceforge.net/xsd/utfxdoc_1_0/utfxdoc.xsd http://utf-x.sourceforge.net/xsd/utfxdoc_1_0/utfxdoc.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:utfx="http://utfx.org/test-definition">
    <ud:title>Guide for Developers</ud:title>
    <ud:subtitle>Unit Testing Framework - XSLT</ud:subtitle>
    <ud:author>Jacek Radajewski</ud:author>
    <ud:version>$Revision$</ud:version>
    <ud:date>$Date$</ud:date>
    <ud:sect1 id="environment">
        <ud:title>Development Environment</ud:title>
        <ud:sect2 id="recommended_tools">
            <ud:title>Recommended Tools</ud:title>

            <ud:para>This section contains a list of recommended development
                tools. These tools have been chosen because they are free (or
                very cheap) and the project has been already correctly
                configured to work with these tools.</ud:para>
            <ud:para>Most tools listed here are optional, but some, such as a
                Java compiler are obviously required.</ud:para>
            <ud:sect3 id="jdk">
                <ud:title>JDK 5.0</ud:title>
                <ud:para>UTF-X uses Java 5 language features so you'll need Java
                    5 or later. UTF-X will not compile or run on earlier
                    versions of Java.</ud:para>
            </ud:sect3>
            <ud:sect3 id="eclipse">
                <ud:title>Eclipse 3.2</ud:title>
                <ud:para><ud:link url="http://eclipse.org">Eclipse</ud:link> is
                    the preferred IDE. UTF-X has already been configured to work
                    correctly with Eclipse and the configuration files are
                    stored in the subversion repository together with the source
                    code. When you checkout the project from within Eclipse,
                    Eclipse will read the configuration files and you will be
                    ready to cut code.</ud:para>
            </ud:sect3>
            <ud:sect3>
                <ud:title>Subversion client</ud:title>
                <ud:para>In order to checkout UTF-X from within Eclipse you will
                    need a subversion plugin called <ud:link
                        url="http://subclipse.tigris.org">Subclipse</ud:link>.
                    Detailed instruction on how to install subclipse are
                    available <ud:link
                        url="http://subclipse.tigris.org/install.html"
                    >here</ud:link>.</ud:para>
                <ud:para>In addition to subclipse you may also want to install a
                    stand alone subverion client. <ud:link
                        url="http://tortoisesvn.tigris.org/">TortoiseSVN
                    1.4.1</ud:link> is a Microsoft Windows shell extension which
                    allows you perform subversion operation directly from
                    Windows Explorer. You can <ud:link
                        url="http://subversion.tigris.org/project_packages.html"
                        >download subversion</ud:link> source or binaries for
                    most platforms.</ud:para>
                <ud:note>Most Linux distributions already ship with
                subversion.</ud:note>
            </ud:sect3>
            <ud:sect3 id="ant">
                <ud:title>Ant 1.6.5</ud:title>
                <ud:para><ud:link url="http://ant.apache.org">Ant</ud:link> is
                    used for various tasks including building, documentation
                    generation and testing.</ud:para>
            </ud:sect3>
            <ud:sect3 id="oxygenxml">
                <ud:title><![CDATA[<oXygen/>]]> XML Editor 7.2 plugin for
                    Eclipse</ud:title>
                <ud:para>
                    <ud:link url="http://www.oxygenxml.com/"
                        ><![CDATA[<oXygen/>]]> XML Editor 7.2</ud:link> plugin
                    for the Eclipse platform provides a vast range of
                    functionality for working with XML, XSLT, XSL:FO, XML
                    Schemas and XPath. If you are mainly a Java developer and
                    are not planning on doing a lot of work with XML and XSLT
                    then functionalities provided by may be sufficient to you.
                    Also, you may already have a different XML/XSL authoring
                    tool such as XML Spy.</ud:para>
            </ud:sect3>
        </ud:sect2>
        <ud:sect2>
            <ud:title>Configuring Your Environment</ud:title>
            <ud:para>This section explains how to configure your development
                environment for UTF-X development. This section only covers
                general configuration and tools listed in the <ud:xref
                    idref="recommended_tools"/> section.</ud:para>
            <ud:sect3>
                <ud:title>Checkout project from subversion</ud:title>
                <ud:para>This section shows how to checkout a UTF-X module from
                    the subversion repository using the Eclipse 3.2 IDE. The
                    subversion modules contain Eclipse configuration files and
                    if you follow the process described below your project
                    environment will be configured correctly after the initial
                    checkout.</ud:para>
                <ud:para>When checking the <ud:code>HEAD</ud:code> of the tree
                    (or trunk) please make sure you checkout the
                    <ud:code>trunk</ud:code> directory as shown in a screenshot
                    below.</ud:para>
                <ud:para> Our subversion repository is at <ud:link
                        url="https://utf-x.svn.sourceforge.net/svnroot/utf-x"
                        >https://utf-x.svn.sourceforge.net/svnroot/utf-x</ud:link>
                </ud:para>

                <!--
                <para>Updating web site content:</para>
                <ordered_list>
                    <item>Login to shell.sourceforge.net using a SSH client and
                        your sourceforge account.</item>
                    <item>Change directory to
                            <code>/home/groups/u/ut/utf-x/htdocs/new</code></item>
                    <item>
                        <code>svn update</code>
                    </item>
                </ordered_list>
-->
                <ud:para>Subversion repository contains the following modules:</ud:para>
                <ud:ordered_list>
                    <ud:item><ud:code>utf-x-framework</ud:code> the framework</ud:item>
                    <ud:item>
                        <ud:code>utf-x-doc</ud:code> the UTF-X Documentation
                        package </ud:item>
                    <ud:item>
                        <ud:code>utf-x-website</ud:code> UTF-X web site at
                        sourceforge.net </ud:item>
                </ud:ordered_list>

                <ud:para>The following is a step-by-step guide to checking out
                    project from within Eclipse:</ud:para>
                <ud:para>From the File menu select 'New Project'. A windows wil
                    pop up in which you need to expand the SVN item and select
                    'Checkout Projects from SVN'.</ud:para>
                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_1.png"
                        width="525px"/>
                    <ud:caption>'Checkout Projects from SVN'</ud:caption>
                </ud:figure>
                <ud:para>Click 'Next' and select 'Create a new repository
                    location'.</ud:para>
                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_2.png"
                        width="530px"/>
                    <ud:caption>Create a repository location</ud:caption>
                </ud:figure>

                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_3.png"
                        width="530px"/>
                    <ud:caption>Create location</ud:caption>
                </ud:figure>

                <ud:para>???</ud:para>
                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_4.png"
                        width="530px"/>
                    <ud:caption>Select what you want to checkout</ud:caption>
                </ud:figure>

                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_5.png"
                        width="530px"/>
                    <ud:caption/>
                </ud:figure>


                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_6.png"
                        width="530px"/>
                    <ud:caption/>
                </ud:figure>

                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_7.png"
                        width="538px"/>
                    <ud:caption/>
                </ud:figure>

                <ud:figure>
                    <ud:img src="images/eclipse/svn_checkout_8.png"
                        width="538px"/>
                    <ud:caption/>
                </ud:figure>



            </ud:sect3>
            <ud:sect3>
                <ud:title>Configuring XML Catalog</ud:title>
                <ud:para>Project root directory contains an <ud:link
                        url="http://www.oasis-open.org/committees/entity/spec-2001-08-06.html"
                        >XML Catalog</ud:link> file
                    <ud:code>catalog.xml</ud:code> file which is used by various
                    UTF-X processes to resolve PUBLIC identifiers. You should
                    tell the <![CDATA[<oXygen/>]]> XML editor about this catalog
                    file so it knows where to find relevant DTDs.</ud:para>
